export const SKILLS_CONFIG = [
  {
    id: 'webdev',
    tag: 'SK_01',
    wrapperClass: 'webdev-wrapper',
    cardClass: 'webdev-card',
    activeColor: 'red',
    threshold: 0.15,
    resolved: {
      header: 'SKILL_01 // WEB DEVELOPMENT',
      stackId: 'FULL_STACK_ARCH',
      confidence: '99.4%',
      frameworks: 'REACT / NEXT / LARAVEL',
      latency: 'OPTIMIZED — 0.02ms',
    },
    unresolved: {
      header: 'SKILL_01 // STACK ANALYZE',
      stackId: 'PARSING_NODES',
      confidence: 'CALCULATING...',
      frameworks: 'FETCHING_MODULES',
      latency: 'LATENCY_CHECK',
    },
  },
  {
    id: 'android',
    tag: 'SK_02',
    wrapperClass: 'android-wrapper',
    cardClass: 'android-card',
    activeColor: 'green',
    threshold: 0.3,
    resolved: {
      header: 'SKILL_02 // ANDROID DEV',
      stackId: 'MOBILE_OS_NODE',
      confidence: '95.8%',
      frameworks: 'KOTLIN / FLUTTER / SDK',
      latency: 'OPTIMIZED — 0.05ms',
    },
    unresolved: {
      header: 'SKILL_02 // MOBILE PIPELINE',
      stackId: 'RESOLVING_SDK',
      confidence: 'CALCULATING...',
      frameworks: 'SCANNING_DEVICE',
      latency: 'LATENCY_CHECK',
    },
  },
  {
    id: 'cyber',
    tag: 'SK_03',
    wrapperClass: 'cyber-wrapper',
    cardClass: 'cyber-card',
    activeColor: 'cyan',
    threshold: 0.45,
    resolved: {
      header: 'SKILL_03 // CYBER SECURITY',
      stackId: 'SEC_AUDIT_PRO',
      confidence: '96.2%',
      frameworks: 'KALI / UBUNTU / NMAP',
      latency: 'SHIELD — 0.01ms',
    },
    unresolved: {
      header: 'SKILL_03 // THREAT AUDIT',
      stackId: 'CHECKING_VULN',
      confidence: 'CALCULATING...',
      frameworks: 'PROBING_PORTS',
      latency: 'DEFENSE_SYNC',
    },
  },
  {
    id: 'net',
    tag: 'SK_04',
    wrapperClass: 'net-wrapper',
    cardClass: 'net-card',
    activeColor: 'red',
    threshold: 0.6,
    resolved: {
      header: 'SKILL_04 // NETWORK INFRA',
      stackId: 'NET_TOPOLOGY_V2',
      confidence: '94.7%',
      frameworks: 'MIKROTIK / CISCO / VPN',
      latency: 'LOW LATENCY — 0.03ms',
    },
    unresolved: {
      header: 'SKILL_04 // ROUTE SCAN',
      stackId: 'PROBING_SUBNET',
      confidence: 'CALCULATING...',
      frameworks: 'RESOLVING_VLAN',
      latency: 'PING_GATEWAY',
    },
  },
  {
    id: 'db',
    tag: 'SK_05',
    wrapperClass: 'db-wrapper',
    cardClass: 'db-card',
    activeColor: 'cyan',
    threshold: 0.75,
    resolved: {
      header: 'SKILL_05 // DATABASE MGMT',
      stackId: 'DATA_ENGINE_V3',
      confidence: '96.8%',
      frameworks: 'POSTGRES / MYSQL / MONGO',
      latency: 'OPTIMIZED — 0.03ms',
    },
    unresolved: {
      header: 'SKILL_05 // DB QUERY SYNC',
      stackId: 'CONNECTING_NODES',
      confidence: 'CALCULATING...',
      frameworks: 'FETCHING_SCHEMA',
      latency: 'LATENCY_CHECK',
    },
  },
  {
    id: 'uiux',
    tag: 'SK_06',
    wrapperClass: 'uiux-wrapper',
    cardClass: 'uiux-card',
    activeColor: 'green',
    threshold: 0.9,
    resolved: {
      header: 'SKILL_06 // UI/UX DESIGN',
      stackId: 'DESIGN_SYSTEM_PRO',
      confidence: '95.0%',
      frameworks: 'FIGMA / PROTOTYPE / HUD',
      latency: 'OPTIMIZED — 0.03ms',
    },
    unresolved: {
      header: 'SKILL_06 // WIREFRAME SYNC',
      stackId: 'GENERATING_FLOW',
      confidence: 'CALCULATING...',
      frameworks: 'PARSING_CANVAS',
      latency: 'RENDER_CHECK',
    },
  },
]
