export const developerSignals = [
  {
    id: 'software',
    phase: '01/04',
    label: 'INITIAL TELEMETRY // STREAM',
    title: 'WEB & MOBILE SYSTEMS',
    subtitle: 'REACT • NEXT.JS • KOTLIN • POSTGRESQL',
    status: 'SCANNING',
    statusColor: 'cyan',
    start: 0,
    end: 0.25,
    tags: ['REACT / NODE', 'KOTLIN ANDROID', 'REST / GRAPHQL', 'POSTGRESQL'],
    metrics: { freq: '2.48 GHz', latency: '0.04 ms', accuracy: '98.6%' },
  },
  {
    id: 'infra',
    phase: '02/04',
    label: 'SECURITY & INFRASTRUCTURE',
    title: 'NETWORK & CYBER SECURITY',
    subtitle: 'MIKROTIK • CISCO • OWASP • TLS 1.3',
    status: 'ANALYZING',
    statusColor: 'cyan',
    start: 0.25,
    end: 0.5,
    tags: ['MIKROTIK / CISCO', 'VLAN & BGP', 'OWASP SEC', 'ZERO TRUST'],
    metrics: { freq: '3.60 GHz', latency: '0.02 ms', accuracy: '99.4%' },
  },
  {
    id: 'spatial',
    phase: '03/04',
    label: 'DATA & SPATIAL INTELLIGENCE',
    title: 'QGIS & DATA PIPELINES',
    subtitle: 'PYTHON • PANDAS • QGIS • FIGMA UI/UX',
    status: 'RESOLVING',
    statusColor: 'orange',
    start: 0.5,
    end: 0.75,
    tags: ['PYTHON EDA', 'QGIS MAPPING', 'FIGMA DESIGN', 'MULTI-DOMAIN'],
    metrics: { freq: '5.80 GHz', latency: '0.01 ms', accuracy: '99.9%' },
  },
  {
    id: 'identity',
    phase: '04/04',
    label: 'PROFILE COMPLETE // IDENTIFIED',
    title: 'CLYNTEN BILLIAM PALAD',
    subtitle: 'FULL STACK DEVELOPER & SYSTEM ARCHITECT',
    status: 'VERIFIED IDENTITY',
    statusColor: 'green',
    start: 0.75,
    end: 1.0,
    tags: ['SYS_CORE v4.8', 'FULL STACK ARCH', 'VERIFIED PROFILE', 'READY'],
    metrics: { freq: '10.0 GHz', latency: '< 0.01 ms', accuracy: '100.0%' },
  },
]

export const rawDataStreams = [
  { raw: 'SYS_00482', resolved: 'SYSTEM DESIGN', final: 'FULL STACK ARCHITECTURE' },
  { raw: 'WEB_29381', resolved: 'WEB DEVELOPMENT', final: 'INTERACTIVE UI / 3D' },
  { raw: 'APP_55192', resolved: 'ANDROID SDK', final: 'KOTLIN / JETPACK' },
  { raw: 'SEC_71829', resolved: 'CYBER SECURITY', final: 'TLS 1.3 / OWASP 10' },
  { raw: 'NET_82710', resolved: 'NETWORK ROUTING', final: 'MIKROTIK / CISCO VLAN' },
  { raw: 'DB_99481', resolved: 'DATABASE MGMT', final: 'POSTGRESQL / MYSQL' },
  { raw: 'GIS_03819', resolved: 'GEOSPATIAL SYS', final: 'QGIS / SPATIAL MAPPING' },
]